server {
    listen 127.0.0.1:8080;
    listen 127.0.0.1:8081;
    listen 127.0.0.1:8082;
    root www;
    server_name localhost 127.0.0.1 sumeralp.com;
    client_max_body_size 10m;
    location /
    {
        autoindex on;
        index about.html index.html;
    }
    location /km
    {
        autoindex on;
        return 301 index.html;
    }
}

server {
    listen 127.0.0.1:9090;
    listen 127.0.0.1:9091;
    root www2;
    server_name localhost 127.0.0.1 test.com;
    client_max_body_size 20m;

    location /
    {
        autoindex on;
        allowed_methods GET;
        index about.html;
    }
}