server {
    listen 0.0.0.0:8080 0.0.0.0:8080;
	root www;
	server_name sumeralp.com sumeralp asd.com;
	client_max_body_size 0;
	error_page 404 ./error_page/not_found;

	location /
	{
		allowed_methods GET;
		index index.html;
	}
	client_max_body_size 5k;
}
server {
    listen 0.0.0.0:8080 default_server;
	root www2;
	server_name test.com;
	client_max_body_size 400m;

	location /
	{
		allowed_methods GET;
		index index.html;
	}
	location /docs.html
	{
		allowed_methods GET SET;
		autoindex on;
		index index.html;
	}
}